version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: hackday_backend
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - PORT=8000
      - ENV=development
    volumes:
      # 開発時のホットリロード用（本番では削除）
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 必要に応じてデータベースサービスを追加
  # postgres:
  #   image: postgres:15
  #   container_name: hackday_postgres
  #   environment:
  #     POSTGRES_DB: hackday
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

  # Redis（キャッシュ用）
  # redis:
  #   image: redis:7-alpine
  #   container_name: hackday_redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

# volumes:
  # postgres_data:

networks:
  default:
    name: hackday_network
